# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SketchAndStitchCompanion' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SketchAndStitchCompanion

  pod 'BlueSocket'

  target 'SketchAndStitchCompanionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SketchAndStitchCompanionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
