# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sketch & Stitch 3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'BlueSocket'
  # Pods for Sketch & Stitch 3

  target 'Sketch & Stitch 3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Sketch & Stitch 3UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
